### PR TITLE
Allow jsonschema >4.0.0

### PR DESCRIPTION
**Pull request by MartinWallgren**
### Applicable Issues
#54 Dependency to jsonschema is really old

### Description of the Change
Open up the version range to jsonschema to allow any version, leaving the version constraint to the user of this lib.

### Alternate Designs

One possibility could be to just open up for version 4
 
`jsonschema >= 3.0.0,<5`

### Benefits

More people can use this lib.

### Possible Drawbacks
jsonschema >4 might not be compatible.

### Sign-off

Developer's Certificate of Origin 1.1

By making a contribution to this project, I certify that:

(a) The contribution was created in whole or in part by me and I
    have the right to submit it under the open source license
    indicated in the file; or

(b) The contribution is based upon previous work that, to the best
    of my knowledge, is covered under an appropriate open source
    license and I have the right under that license to submit that
    work with modifications, whether created in whole or in part
    by me, under the same open source license (unless I am
    permitted to submit under a different license), as indicated
    in the file; or

(c) The contribution was provided directly to me by some other
    person who certified (a), (b) or (c) and I have not modified
    it.

(d) I understand and agree that this project and the contribution
    are public and that a record of the contribution (including all
    personal information I submit with it, including my sign-off) is
    maintained indefinitely and may be redistributed consistent with
    this project or the open source license(s) involved.

Signed-off-by: Martin Wallgren martin@wallgren.it

### CODE REVIEW

**Review by t-persson — APPROVED** [review]

**Review by fredjn — APPROVED** [review]

**Comment by mehdihasan** [comment]
Can we have a new release along with this commit? The latest release does not contains this change.
CC: @t-persson @fredjn @MartinWallgren

**Comment by t-persson** [comment]
> Can we have a new release along with this commit? The latest release does not contains this change. CC: @t-persson @fredjn @MartinWallgren

Thanks for the ping. I added a PR for updating to the latest version of Eiffel and when that is merged I'll create a new release.
Sorry for being slow on this.

**Comment by t-persson** [comment]
> > Can we have a new release along with this commit? The latest release does not contains this change. CC: @t-persson @fredjn @MartinWallgren
> 
> Thanks for the ping. I added a PR for updating to the latest version of Eiffel and when that is merged I'll create a new release. Sorry for being slow on this.

Version 3.0.0 has now been uploaded to pypi

**Comment by mehdihasan** [comment]
Thanks a lot for the rapid action!

**Pull request merged**
