### PR TITLE
Update rabbitmq_publisher.py

### PR DESCRIPTION
**Pull request by ebram96**
### Applicable Issues

NA.

### Description of the Change

Use current_thread().name instead of current_thread().getName() to remove deprecation warning.

### Alternate Designs

NA.

### Benefits

Use current_thread().name instead of current_thread().getName() to remove deprecation warning.

### Possible Drawbacks

NA

### Sign-off

Developer's Certificate of Origin 1.1

By making a contribution to this project, I certify that:

(a) The contribution was created in whole or in part by me and I
    have the right to submit it under the open source license
    indicated in the file; or

(b) The contribution is based upon previous work that, to the best
    of my knowledge, is covered under an appropriate open source
    license and I have the right under that license to submit that
    work with modifications, whether created in whole or in part
    by me, under the same open source license (unless I am
    permitted to submit under a different license), as indicated
    in the file; or

(c) The contribution was provided directly to me by some other
    person who certified (a), (b) or (c) and I have not modified
    it.

(d) I understand and agree that this project and the contribution
    are public and that a record of the contribution (including all
    personal information I submit with it, including my sign-off) is
    maintained indefinitely and may be redistributed consistent with
    this project or the open source license(s) involved.

Signed-off-by:  Ebram Shehata ebram96@gmail.com

### CODE REVIEW

**Comment by fredjn** [comment]
Changes look fine, thank you for contributing. However, I am curious to know why the PR template is not used. Was it ignored/removed deliberately, or it there is there something broken with the template propagation from the eiffel-community organization?

**Comment by magnusbaeck** [comment]
PR templates aren't used if you edit files directly from the GitHub web page.

**Comment by ebram96** [comment]
@fredjn @magnusbaeck I think I deliberately skipped using the template in this PR. Why ? I thought it's a really tiny change and I didn't want reviewers going through the template for such a change.

I can -for sure- update the PR with the template contents if you want me to.

**Comment by ebram96** [comment]
@fredjn @magnusbaeck I updated the PR.

**Review by fredjn — APPROVED** [review]

**Review by t-persson — APPROVED** [review]
Missed this one, sorry

**Pull request merged**
